spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
server:
  port: 8081
  max-http-request-header-size: 10MB

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: off

blog:
  thread:
    core-size: 20
    max-size: 100
    keep-alive-time: 10
  highest-role: admin
  default-role: boy,girl
  email-try-count: 3
  blog-page-size: 5
  web-page-size: 9
  password-error-intervalTime: 90000
