spring:
  mail:
    port: 465
    host: smtp.163.com #SMTP服务器地址
    username: dinglei@163.com #登陆账号
    password: dinglei #登陆密码（或授权码）
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      from: dinglei@163.com #邮件发信人（即真实邮箱）
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/vueblog?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://127.0.0.1:9200
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  data:
    redis:
      port: 6379
      password: 123456
      host: 127.0.0.1

logging:
  level:
    web: debug

blog:
  jwt:
    secret: ti8n3439n439t43ld9nv9343ddfer09hti8n3439n439t43ld9nv9343ddfer09ti8n3439n439t43ld9nv9343ddfer09fti8n3439n439t43ld9nv9343ddfer09f
  oss:
    host: https://oss-cn-hangzhou.aliyuncs.com
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: blog
    accessKeyId: accessKeyId
    accessKeySecret: accessKeySecret
