spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mail:
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  profiles:
    default: dev
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
server:
  port: 8081
  max-http-request-header-size: 10MB

logging:
  config: classpath:logback-spring.xml

blog:
  thread:
    core-size: 20
    max-size: 100
    keep-alive-time: 10
  highest-role: admin
  default-role: user
  email-try-count: 3
  blog-page-size: 5
  password-error-intervalTime: 900000
  jwt:
    access-token-expire: 21600
    refresh-token-expire: 604800
