spring:
  mail:
    host: smtp.163.com
    username: 18392423997
    password: RHIVUKVCTFIYLUDJ
    properties:
      from: 18392423997@163.com
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://127.0.0.1:9200
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  data:
    redis:
      port: 6379
      password: 123456
      host: 127.0.0.1

logging:
  level:
    web: debug

blog:
  jwt:
    secret: ti8n3439n439t43ld9nv9343ddfer09hti8n3439n439t43ld9nv9343ddfer09ti8n3439n439t43ld9nv9343ddfer09fti8n3439n439t43ld9nv9343ddfer09f
    expire: 604800


